services:
  postgres:
    image: postgres:16.0-alpine3.17
    container_name: population
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - my_db:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 2s
      timeout: 3s
      retries: 15

  get_data:
    build: .
    command: python -m services.population_loader
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      TARGET_URL: ${TARGET_URL}
      DATABASE_URL: ${DATABASE_URL}

  print_data:
    build: .
    command: python -m services.population_printer
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  my_db: